version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/city-skylines-wiki"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): update to node dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): update"
