name: Content Management

on:
  push:
    paths:
      - "**/*.md"

jobs:
  generate-toc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm
        shell: bash
        run: |
          npm install -g pnpm
          pnpm --version
          pnpm config set store-dir ~/.pnpm-store

      - name: Install dependencies
        run: pnpm install -g markdown-toc

      - name: Generate downloadable file
        run: pnpm run generate -i contents.md -o contents.md
