name: Content Management

on:
  push:
    paths:
      - "**/*.md"

jobs:
  generate-toc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: pnpm install markdown-toc -g
      - run: markdown-toc -i Table-of-contents.md
