name: Content Management

on:
  push:
    paths:
      - "**/*.md"

jobs:
  generate-toc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm
        shell: zsh
        run: |
          npm install -g pnpm
          pnpm setup

      - name: Install markdown-toc
        run: pnpm install -g markdown-toc

      - name: Generate Table of Contents
        run: markdown-toc -i Table-of-contents.md
