name: Content Management

on:
  push:
    paths:
      - "**/*.md"

jobs:
  generate-toc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install markdown-toc
        run: pnpm install markdown-toc -g

      - name: Generate Table of Contents
        run: markdown-toc -i Table-of-contents.md
