name: Deploy to GitHub Pages
on:
  workflow_dispatch:
    inputs:
      unconditional-invoking:
        description: "Deploy Manually"
        type: boolean
        required: true
        default: false

  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docusaurus Cache
        uses: docuactions/cache@v1

      - name: Update Base URL
        run: |
          sed -i 's/baseUrl: "\//baseUrl: "\/Docusaurus-GitPage-Action\//g' docusaurus.config.ts

      - name: Install pnpm
        run: |
          curl -L https://unpkg.com/@pnpm/self-installer | node

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Deploy
        id: deployment
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build
