name: Deploy to GitHub Pages
on:
  workflow_dispatch:
    inputs:
      unconditional-invoking:
        description: "Deploy Manually"
        type: boolean
        required: true
        default: false

  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Cache pnpm store
        id: pnpm-cache
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('city-skylines-wiki/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Cache node modules
        id: node-modules-cache
        uses: actions/cache@v3
        with:
          path: city-skylines-wiki/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('city-skylines-wiki/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install pnpm package manager
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: npm install -g pnpm

      - name: Validate pnpm installation
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install
        working-directory: city-skylines-wiki

      - name: Build
        run: pnpm build
        working-directory: city-skylines-wiki

      - name: Deploy
        id: deployment
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: city-skylines-wiki/build
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
